TRANSACTIONS_PER_SECOND = 10
AVERAGE_BLOCK_INTERVAL_IN_SECONDS = 600

AVERAGE_TRANSACTION_FEE = 0.000062
AVERAGE_TRANSACTION_SIZE_IN_MB = 0.000546

BLOCK_SIZE_IN_MB = 1.0

SIMULATION_RUNS = 2
SIMULATION_LENGTH_IN_SECONDS = 1000

AVERAGE_BLOCK_PROPOGATION_DELAY = 0.42
AVERAGE_TRANSACTION_PROPOGATION_DELAY = 5.1

HAS_TRANSACTIONS = True
TRANSACTION_TECHNIQUE = "Light"

BLOCK_REWARD = 12.5

NODE_COUNT = 3